language: generic
sudo: true

git:
  depth: 1
  
env:
  global:
    - BYOND_VERSION: "512"
    - BYOND_BUILD: "1454"
    - BYOND_MACROS: 2
    
cache:
  directories:
    - $HOME/BYOND-${BYOND_VERSION}.${BYOND_BUILD}
    
addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      
before_script:
  - chmod +x scripts/./install-byond.sh
  - scripts/./install-byond.sh
    
script:
  - (num=`grep -E '\\\\(red|blue|green|black|italic|bold|b|i[^mc])' **/*.dm | wc -l`; echo "$num BYOND text macros (expecting ${BYOND_MACROS} or fewer)"; [ $num -le ${BYOND_MACROS} ])
  - source $HOME/BYOND-${BYOND_VERSION}.${BYOND_BUILD}/byond/bin/byondsetup
  - bash scripts/dm.sh 44BR13.dme
